server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url : jdbc:h2:mem:test
    username : sa
    password :
    platform : h2
    schema : classpath:schema.sql
    driver-class-name: org.h2.Driver
#    data : classpath:data.sql
  jpa:
    hibernate:
#      dialect : org.hibernate.dialect.H2Dialect
      ddl-auto : update
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql : true
    database-platform: org.hibernate.dialect.H2Dialect